version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: root
      POSTGRES_DB: example
    ports:
      - "127.0.0.1:5432:5432"